repos:
  - repo: local
    hooks:
      - id: mypy
        name: Checking static type errors
        entry: poetry run mypy bot.py cloudfeed
        pass_filenames: false
        language: system
        types: [python]
