[tool.poetry]
name = "cloudfeed"
version = "0.1.0"
description = "Discord bot to store articles"
authors = ["João Santos <joaopns05@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
discord-py = "^1.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
mypy = "^0.740.0"
pre-commit = "^1.20"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
